version: '3.8'

networks:
  traefik_network:
    driver: overlay
    attachable: true

volumes:
  lab_documentation:

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - --providers.docker.swarmmode
      - --api.insecure=true
      - --providers.docker.network=traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_network
    deploy:
      placement:
        constraints:
          - node.role == manager
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: Dockerfile
    image: goldfieldlab/dnsmasq:alpine3.13
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/resolv.conf:/etc/resolv.conf
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - traefik_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    command: ["--log-facility=-"]
    labels:
      - traefik.enable=false
    deploy:
      placement:
        constraints:
          - node.role == manager
  ghost:
    image: ghost:alpine
    environment:
      url: "http://gibson.goldtelecom.com/documentation"
    volumes:
      - lab_documentation:/var/lib/ghost/content
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost-router.entrypoints=http
      - traefik.http.routers.ghost-router.rule=Host(`gibson.goldtelecom.com`) && PathPrefix(`/documentation`)
      - traefik.http.routers.ghost-router.middlewares=ghost-middlewares
      - traefik.http.routers.ghost-router.service=ghost-service
      - traefik.http.middlewares.ghost-middlewares.chain.middlewares=ghost-middleware01,ghost-middleware02,ghost-middleware03
      - traefik.http.middlewares.ghost-middleware01.stripprefix.prefixes=/documentation
      - traefik.http.middlewares.ghost-middleware02.redirectregex.regex=^(.*)/documentation$$
      - traefik.http.middlewares.ghost-middleware02.redirectregex.replacement=$$1/documentation/
      - traefik.http.middlewares.ghost-middleware03.replacepathregex.regex=^/documentation/(.*)
      - traefik.http.middlewares.ghost-middleware03.replacepathregex.replacement=$$1
      - traefik.services.ghost-service.loadbalancer.server.port=2368
    networks:
      - traefik_network
    deploy:
      placement:
        constraints:
          - node.role == manager
