version: '3.8'

services:
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: Dockerfile
    image: goldfieldlab/dnsmasq:alpine3.13
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/resolv.conf:/etc/resolv.conf
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    command: ["--log-facility=-"]
